#%RAML 1.0 NamedExample
type: array
example: [
  {
    "empId": "1234",
    "firstName": "Test",
    "lastName": "T1",
    "emailAddress": "test.T1@abc.com",
    "role": "Developer",
    "activeFlag": "Y"
  },
  {
    "empId": "4321",
    "firstName": "Xyz",
    "lastName": "A1",
    "emailAddress": "Xyz.A1@abc.com",
    "role": "Developer",
    "activeFlag": "Y"
  }
]